[ [ 'hello' ],
  [ 'difference', '(', '{}', ')' ],
  [ '{' ],
  [ 'intersection', '(', '{}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Blue"}', ')' ],
  [ '{' ],
  [ 'sphere', '(', '{"arg":10}', ')' ],
  [ '}' ],
  [ 'color', '(', '{"arg":"Red"}', ')' ],
  [ '{' ],
  [ 'cube', '(', '{"arg":15,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ 'union', '(', '{}', ')' ],
  [ '{' ],
  [ 'rotate', '(', '{"arg":[0,90,0]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Lime"}', ')' ],
  [ '{' ],
  [ 'cylinder', '(', '{"h":20,"r":5,"center":true}', ')' ],
  [ '}' ],
  [ '}' ] ]
[ [ 'hello' ],
  [ 'difference', '(', '{}', ')' ],
  [ '{' ],
  [ 'intersection', '(', '{}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Blue"}', ')' ],
  [ '{' ],
  [ 'sphere', '(', '{"arg":10}', ')' ],
  [ '}' ],
  [ 'color', '(', '{"arg":"Red"}', ')' ],
  [ '{' ],
  [ 'cube', '(', '{"arg":15,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ 'union', '(', '{}', ')' ],
  [ '{' ],
  [ 'rotate', '(', '{"arg":[0,90,0]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Lime"}', ')' ],
  [ '{' ],
  [ 'cylinder', '(', '{"h":20,"r":5,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ 'rotate', '(', '{"arg":[90,0,0]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Lime"}', ')' ],
  [ '{' ],
  [ 'cylinder', '(', '{"h":20,"r":5,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ 'color', '(', '{"arg":"Lime"}', ')' ],
  [ '{' ],
  [ 'cylinder', '(', '{"h":20,"r":5,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ '}' ],
  [ 'scale', '(', '{"arg":0.5}', ')' ],
  [ '{' ],
  [ 'translate', '(', '{"arg":[-30,0,-40]}', ')' ],
  [ '{' ],
  [ 'intersection', '(', '{}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Blue"}', ')' ],
  [ '{' ],
  [ 'sphere', '(', '{"arg":10}', ')' ],
  [ '}' ],
  [ 'color', '(', '{"arg":"Red"}', ')' ],
  [ '{' ],
  [ 'cube', '(', '{"arg":15,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ 'translate', '(', '{"arg":[-15,0,-35]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Blue"}', ')' ],
  [ '{' ],
  [ 'sphere', '(', '{"arg":10}', ')' ],
  [ '}' ],
  [ '}' ],
  [ 'translate', '(', '{"arg":[15,0,-35]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Red"}', ')' ],
  [ '{' ],
  [ 'cube', '(', '{"arg":15,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ 'translate', '(', '{"arg":[-7.5,0,-17.5]}', ')' ],
  [ '{' ],
  [ 'rotate', '(', '{"arg":[0,30,0]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Black"}', ')' ],
  [ '{' ],
  [ 'cylinder', '(', '{"r":1,"h":10,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ '}' ],
  [ 'translate', '(', '{"arg":[7.5,0,-17.5]}', ')' ],
  [ '{' ],
  [ 'rotate', '(', '{"arg":[0,-30,0]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Black"}', ')' ],
  [ '{' ],
  [ 'cylinder', '(', '{"r":1,"h":10,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ '}' ],
  [ '}' ],
  [ 'translate', '(', '{"arg":[30,0,-40]}', ')' ],
  [ '{' ],
  [ 'union', '(', '{}', ')' ],
  [ '{' ],
  [ 'rotate', '(', '{"arg":[0,90,0]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Lime"}', ')' ],
  [ '{' ],
  [ 'cylinder', '(', '{"h":20,"r":5,"center":true}', ')' ],
  [ '}' ],
  [ '}' ] ]
[ [ 'hello' ],
  [ 'difference', '(', '{}', ')' ],
  [ '{' ],
  [ 'intersection', '(', '{}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Blue"}', ')' ],
  [ '{' ],
  [ 'sphere', '(', '{"arg":10}', ')' ],
  [ '}' ],
  [ 'color', '(', '{"arg":"Red"}', ')' ],
  [ '{' ],
  [ 'cube', '(', '{"arg":15,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ 'union', '(', '{}', ')' ],
  [ '{' ],
  [ 'rotate', '(', '{"arg":[0,90,0]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Lime"}', ')' ],
  [ '{' ],
  [ 'cylinder', '(', '{"h":20,"r":5,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ 'rotate', '(', '{"arg":[90,0,0]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Lime"}', ')' ],
  [ '{' ],
  [ 'cylinder', '(', '{"h":20,"r":5,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ 'color', '(', '{"arg":"Lime"}', ')' ],
  [ '{' ],
  [ 'cylinder', '(', '{"h":20,"r":5,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ '}' ],
  [ 'scale', '(', '{"arg":0.5}', ')' ],
  [ '{' ],
  [ 'translate', '(', '{"arg":[-30,0,-40]}', ')' ],
  [ '{' ],
  [ 'intersection', '(', '{}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Blue"}', ')' ],
  [ '{' ],
  [ 'sphere', '(', '{"arg":10}', ')' ],
  [ '}' ],
  [ 'color', '(', '{"arg":"Red"}', ')' ],
  [ '{' ],
  [ 'cube', '(', '{"arg":15,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ 'translate', '(', '{"arg":[-15,0,-35]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Blue"}', ')' ],
  [ '{' ],
  [ 'sphere', '(', '{"arg":10}', ')' ],
  [ '}' ],
  [ '}' ],
  [ 'translate', '(', '{"arg":[15,0,-35]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Red"}', ')' ],
  [ '{' ],
  [ 'cube', '(', '{"arg":15,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ 'translate', '(', '{"arg":[-7.5,0,-17.5]}', ')' ],
  [ '{' ],
  [ 'rotate', '(', '{"arg":[0,30,0]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Black"}', ')' ],
  [ '{' ],
  [ 'cylinder', '(', '{"r":1,"h":10,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ '}' ],
  [ 'translate', '(', '{"arg":[7.5,0,-17.5]}', ')' ],
  [ '{' ],
  [ 'rotate', '(', '{"arg":[0,-30,0]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Black"}', ')' ],
  [ '{' ],
  [ 'cylinder', '(', '{"r":1,"h":10,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ '}' ],
  [ '}' ],
  [ 'translate', '(', '{"arg":[30,0,-40]}', ')' ],
  [ '{' ],
  [ 'union', '(', '{}', ')' ],
  [ '{' ],
  [ 'rotate', '(', '{"arg":[0,90,0]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Lime"}', ')' ],
  [ '{' ],
  [ 'cylinder', '(', '{"h":20,"r":5,"center":true}', ')' ],
  [ '}' ],
  [ '}' ],
  [ 'rotate', '(', '{"arg":[90,0,0]}', ')' ],
  [ '{' ],
  [ 'color', '(', '{"arg":"Lime"}', ')' ],
  ... 21 more items ]
hello  difference ( {} )  {  intersection ( {} )  {  color ( {"arg":"Blue"} )  {  sphere ( {"arg":10} )  }  color ( {"arg":"Red"} )  {  cube ( {"arg":15,"center":true} )  }  }  union ( {} )  {  rotate ( {"arg":[0,90,0]} )  {  color ( {"arg":"Lime"} )  {  cylinder ( {"h":20,"r":5,"center":true} )  }  }  rotate ( {"arg":[90,0,0]} )  {  color ( {"arg":"Lime"} )  {  cylinder ( {"h":20,"r":5,"center":true} )  }  }  color ( {"arg":"Lime"} )  {  cylinder ( {"h":20,"r":5,"center":true} )  }  }  }  scale ( {"arg":0.5} )  {  translate ( {"arg":[-30,0,-40]} )  {  intersection ( {} )  {  color ( {"arg":"Blue"} )  {  sphere ( {"arg":10} )  }  color ( {"arg":"Red"} )  {  cube ( {"arg":15,"center":true} )  }  }  translate ( {"arg":[-15,0,-35]} )  {  color ( {"arg":"Blue"} )  {  sphere ( {"arg":10} )  }  }  translate ( {"arg":[15,0,-35]} )  {  color ( {"arg":"Red"} )  {  cube ( {"arg":15,"center":true} )  }  }  translate ( {"arg":[-7.5,0,-17.5]} )  {  rotate ( {"arg":[0,30,0]} )  {  color ( {"arg":"Black"} )  {  cylinder ( {"r":1,"h":10,"center":true} )  }  }  }  translate ( {"arg":[7.5,0,-17.5]} )  {  rotate ( {"arg":[0,-30,0]} )  {  color ( {"arg":"Black"} )  {  cylinder ( {"r":1,"h":10,"center":true} )  }  }  }  }  translate ( {"arg":[30,0,-40]} )  {  union ( {} )  {  rotate ( {"arg":[0,90,0]} )  {  color ( {"arg":"Lime"} )  {  cylinder ( {"h":20,"r":5,"center":true} )  }  }  rotate ( {"arg":[90,0,0]} )  {  color ( {"arg":"Lime"} )  {  cylinder ( {"h":20,"r":5,"center":true} )  }  }  color ( {"arg":"Lime"} )  {  cylinder ( {"h":20,"r":5,"center":true} )  }  }  translate ( {"arg":[-10,0,-35]} )  {  rotate ( {"arg":[0,90,0]} )  {  color ( {"arg":"Lime"} )  {  cylinder ( {"h":20,"r":5,"center":true} )  }  }  }  translate ( {"arg":[10,0,-35]} )  {  rotate ( {"arg":[90,0,0]} )  {  color ( {"arg":"Lime"} )  {  cylinder ( {"h":20,"r":5,"center":true} )  }  }  }  translate ( {"arg":[30,0,-35]} )  {  color ( {"arg":"Lime"} )  {  cylinder ( {"h":20,"r":5,"center":true} )  }  }  translate ( {"arg":[5,0,-17.5]} )  {  rotate ( {"arg":[0,-20,0]} )  {  color ( {"arg":"Black"} )  {  cylinder ( {"r":1,"h":10,"center":true} )  }  }  }  translate ( {"arg":[-5,0,-17.5]} )  {  rotate ( {"arg":[0,30,0]} )  {  color ( {"arg":"Black"} )  {  cylinder ( {"r":1,"h":10,"center":true} )  }  }  }  translate ( {"arg":[15,0,-17.5]} )  {  rotate ( {"arg":[0,-45,0]} )  {  color ( {"arg":"Black"} )  {  cylinder ( {"r":1,"h":10,"center":true} )  }  }  }  }  translate ( {"arg":[-20,0,-22.5]} )  {  rotate ( {"arg":[0,45,0]} )  {  color ( {"arg":"Black"} )  {  cylinder ( {"r":1,"h":10,"center":true} )  }  }  }  translate ( {"arg":[20,0,-22.5]} )  {  rotate ( {"arg":[0,-45,0]} )  {  color ( {"arg":"Black"} )  {  cylinder ( {"r":1,"h":10,"center":true} )  }  }  }  }  echo ( {"version":["version","(",null,")"]} )  
